---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: maadharapp
  name: java-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: maadharapp
    spec:
      containers:
      - image: kamal22yards/maadharapp
        name: maadharapp
        ports:
        - name: maadharapp
          containerPort: 8081 
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: maadharapp
  name: maadharapp
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    name: maadharapp